import { StyleSheet } from "react-native";
import { COLORS } from "@/src/themes/themes";

export const CreateGameFormStyles = StyleSheet.create({
    container: {
        width: '100%',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 16,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#edf2f7',
    },
    sectionTitle: {
        fontSize: 12,
        fontWeight: '800',
        color: COLORS.primary,
        textTransform: 'uppercase',
        letterSpacing: 1.5,
    },
    label: {
        fontSize: 13,
        fontWeight: '700',
        color: '#718096',
        marginBottom: 8,
    },
    input: {
        backgroundColor: '#f7fafc',
        borderRadius: 12,
        padding: 14,
        fontSize: 16,
        color: '#1a202c',
        borderWidth: 1,
        borderColor: '#edf2f7',
        marginBottom: 16,
    },
    row: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 4,
    },
    column: {
        flex: 1,
    },
    sportChips: {
        flexDirection: 'row',
        marginBottom: 20,
    },
    sportChip: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: '#edf2f7',
        marginRight: 8,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    sportChipActive: {
        backgroundColor: COLORS.primary + '15',
        borderColor: COLORS.primary,
    },
    sportChipText: {
        fontSize: 14,
        color: '#4a5568',
        fontWeight: '600',
    },
    sportChipTextActive: {
        color: COLORS.primary,
        fontWeight: 'bold',
    },
    sliderContainer: {
        marginBottom: 24,
    },
    sliderLabelRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    sliderValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.primary,
    },
    errorText: {
        color: '#e53e3e',
        fontSize: 13,
        fontWeight: '600',
        marginTop: 10,
        marginBottom: 16,
        textAlign: 'center',
    },
    submitButton: {
        backgroundColor: COLORS.primary,
        borderRadius: 16,
        padding: 18,
        alignItems: 'center',
        marginTop: 10,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    submitButtonDisabled: {
        backgroundColor: '#cbd5e0',
        shadowOpacity: 0,
        elevation: 0,
    },
    toggleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        backgroundColor: '#f7fafc',
        borderRadius: 12,
        paddingHorizontal: 14,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#edf2f7',
    },
    toggleLabelGroup: {
        flex: 1,
        marginRight: 12,
    },
    toggleTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#2d3748',
        marginBottom: 2,
    },
    toggleDescription: {
        fontSize: 12,
        color: '#718096',
    },
    chipGroupContainer: {
        marginBottom: 20,
    },
    dateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 14,
        paddingHorizontal: 4,
        borderBottomWidth: 1,
        borderBottomColor: '#edf2f7',
        marginBottom: 4,
    },
    dateLabel: {
        fontSize: 16,
        color: '#718096',
        fontWeight: '500',
    },
    dateValue: {
        fontSize: 16,
        color: '#1a202c',
        fontWeight: '600',
    },
    tickerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#f7fafc',
        padding: 12,
        borderRadius: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#edf2f7',
    },
    tickerControls: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    tickerButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#edf2f7',
    },
    tickerButtonText: {
        fontSize: 20,
        fontWeight: '600',
        color: COLORS.primary,
    },
    tickerValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1a202c',
        width: 40,
        textAlign: 'center',
        paddingVertical: 4,
    }
});
